#!/system/bin/sh
stoppedmpdecision=
for x in `find /sys -name '*enable_auto_hotplug*'`; do
  echo "Kernel supports auto_hotplug. Enabling it, and disabling MPDecision."
  echo 1 > $x
  [ ! $stoppedmpdecision ] && stoppedmpdecision=0 && stop mpdecision
done

if [ -e /sys/devices/system/cpu/cpufreq/kthermal ]; then
  echo "Kernel has kthermal module. Stopping `getprop qcom.thermal`"
  stop `getprop qcom.thermal`
fi

for x in `find /sys -name cpufreq`; do for y in `ls $x`; do   
  chown system.system $x/$y
  chmod 664 $x/$y
done; done
