#!/system/bin/sh
nuclearwinter

# give mpdecision 60 seconds to start in case we missed it
(
  secs=60
  while [ $secs -gt 0 ]; do
    log "Waiting for mpdecision to start before one last nuclearwinter"
    secs=`expr $secs - 1`
    if pgrep -f mpdecision; then
      nuclearwinter
      break
    fi
    sleep 1
  done
) &
