#!/system/bin/sh
mount -o remount,rw,noatime,nodiratime -t ext3 /dev/block/mmcblk0p25 /system
initPath=/system/etc/init.d/99sonic
OLDBOOST=$(cat /sys/class/misc/soundcontrol/volume_boost)
OLDPERF=$(cat /sys/class/misc/soundcontrol/highperf_enabled)
echo "+++++++++++++++++++++++++++++++++++++++++++++++++++"
echo "+                                                 +"
echo "+ 	        Sound Control                   +"
echo "+                                                 +"
echo "+++++++++++++++++++++++++++++++++++++++++++++++++++"
echo
echo "Current Settings: Volume Boost - $OLDBOOST"
echo "                  High Performance Mode - $OLDPERF"
echo "0) Disable Volume Boost"
echo "1) Enable Lowest Level of Volume Boost"
echo "2) Enable Mid-level Volume Boost"
echo "3) Enable Max Volume Boost"
echo "4) Enable High Performance Mode (this may increase battery drain)"
echo "5) Disable High Performance Mode"
echo "B) Set Current Settings on Boot"
echo "R) Return to Main Menu"
echo "X) Exit"
echo
echo
echo -n "Enter option: "
read opt
if [ "$?" != "1" ]
  then
    case $opt in
   0) echo "0" > /sys/class/misc/soundcontrol/volume_boost && echo "Volume Boost Disabled" && sleep 2 && sh /system/xbin/popcorn_sc;;
   1) echo "1" > /sys/class/misc/soundcontrol/volume_boost && echo "Volume Boost Enabled with a Value of 1" && sleep 2 && sh /system/xbin/popcorn_sc;;
   2) echo "2" > /sys/class/misc/soundcontrol/volume_boost && echo "Volume Boost Enabled with a Value of 2" && sleep 2 && sh /system/xbin/popcorn_sc;;
   3) echo "3" > /sys/class/misc/soundcontrol/volume_boost && echo "Volume Boost Enabled with a Value of 3" && sleep 2 && sh /system/xbin/popcorn_sc;;
   4) echo "1" > /sys/class/misc/soundcontrol/highperf_enabled && echo "High Performance Mode Enabled" && sleep 2 && sh /system/xbin/popcorn_sc;;
   5) echo "0" > /sys/class/misc/soundcontrol/highperf_enabled && echo "High Performance Mode Disabled" && sleep 2 && sh /system/xbin/popcorn_sc;;
   B) sed -i "s|^VolBoost=.*|VolBoost=$OLDBOOST|" $initPath && busybox sed -i "s|^HighPerf=.*|HighPerf=$OLDPERF|" $initPath && echo "Settings set on boot" && sleep 2 && sh /system/xbin/popcorn_sc;;
   R) sh /system/xbin/popcorn;;
   X) exit 1;;
   *) echo "Invalid option" && sleep 2 && sh /system/xbin/popcorn_sc;;     

    esac
  fi

