#!/system/bin/sh
mount -o remount,rw,noatime,nodiratime -t ext3 /dev/block/mmcblk0p25 /system
initPath=/system/etc/init.d/99sonic
OLDMPU=$(cat /sys/kernel/debug/smartreflex/sr_mpu/autocomp)
OLDCORE=$(cat /sys/kernel/debug/smartreflex/sr_core/autocomp)
OLDIVA=$(cat /sys/kernel/debug/smartreflex/sr_iva/autocomp)
echo "+++++++++++++++++++++++++++++++++++++++++++++++++++"
echo "+                                                 +"
echo "+ 		Smart Reflex Toggle             +"
echo "+                                                 +"
echo "+++++++++++++++++++++++++++++++++++++++++++++++++++"
echo
echo "Current Settings: MPU - $OLDMPU"
echo "                  IVA - $OLDIVA"
echo "                  Core - $OLDCORE"
echo "1) Enable SmartReflex for MPU"
echo "2) Disable SmartReflex for MPU"
echo "3) Enable SmartReflex for IVA"
echo "4) Disable SmartReflex for IVA"
echo "5) Enable SmartReflex for Core"
echo "6) Disable SmartReflex for Core"
echo "B) Set Current Settings on Boot"
echo "R) Return to Main Menu"
echo "X) Exit"
echo
echo
echo
echo -n "Enter option: "
read opt
if [ "$?" != "1" ]
  then
    case $opt in
      1) echo "1" > /sys/kernel/debug/smartreflex/sr_mpu/autocomp && echo "SmartReflex for MPU is ENABLED" && sleep 2 && sh /system/xbin/popcorn_sr;;
      2) echo "0" > /sys/kernel/debug/smartreflex/sr_mpu/autocomp && echo "SmartReflex for MPU is DISABLED" && sleep 2 && sh /system/xbin/popcorn_sr;;
      3) echo "1" > /sys/kernel/debug/smartreflex/sr_iva/autocomp && echo "SmartReflex for IVA is ENABLED" && sleep 2 && sh /system/xbin/popcorn_sr;;
      4) echo "0" > /sys/kernel/debug/smartreflex/sr_iva/autocomp && echo "SmartReflex for IVA is DISABLED" && sleep 2 && sh /system/xbin/popcorn_sr;;
      5) echo "1" > /sys/kernel/debug/smartreflex/sr_core/autocomp && echo "SmartReflex for CORE is ENABLED" && sleep 2 && sh /system/xbin/popcorn_sr;;
      6) echo "0" > /sys/kernel/debug/smartreflex/sr_core/autocomp && echo "SmartReflex for CORE is DISABLED" && sleep 2 && sh /system/xbin/popcorn_sr;;
      B) sed -i "s|^srMPU=.*|srMPU=$OLDMPU|" $initPath && busybox sed -i "s|^srIVA=.*|srIVA=$OLDIVA|" $initPath && busybox sed -i "s|^srCORE=.*|srCORE=$OLDCORE|" $initPath && echo "Settings set on boot" && sleep 2 && sh /system/xbin/popcorn_sr;;
      R) sh /system/xbin/popcorn;;
      X) exit 1;;
      *) echo "Invalid option" && sleep 2 && sh /system/xbin/popcorn_sr;;
    esac
  fi

