#!/system/bin/sh
mount -o remount,rw,noatime,nodiratime -t ext3 /dev/block/mmcblk0p25 /system
initPath=/system/etc/init.d/99sonic
OLD=$(cat /sys/devices/system/cpu/cpu0/cpufreq/gpu_oc)
echo "+++++++++++++++++++++++++++++++++++++++++++++++++++"
echo "+                                                 +"
echo "+ 		GPU Overclock                   +"
echo "+                                                 +"
echo "+++++++++++++++++++++++++++++++++++++++++++++++++++"
echo
echo "Current Setting: $OLD"
echo "Overclock GPU to the following preset values:"
echo "0) 307MHz--default"
echo "1) 384MHz"
echo "2) 460MHz"
echo "3) 512MHz"
echo "B) Set Current Settings on Boot"
echo "R) Return to Main Menu"
echo "X) Exit Script"
echo
echo
echo
echo -n "Enter option: "
read opt
if [ "$?" != "1" ]
  then
    case $opt in
      0) echo "0" > /sys/devices/system/cpu/cpu0/cpufreq/gpu_oc && echo "GPU Now Clocked at 307 MHz" && sleep 2 && sh /system/xbin/popcorn_gpu;;
      1) echo "1" > /sys/devices/system/cpu/cpu0/cpufreq/gpu_oc && echo "GPU Now Clocked at 384 MHz" && sleep 2 && sh /system/xbin/popcorn_gpu;;
      2) echo "2" > /sys/devices/system/cpu/cpu0/cpufreq/gpu_oc && echo "GPU Now Clocked at 460 MHz" && sleep 2 && sh /system/xbin/popcorn_gpu;;
      3) echo "3" > /sys/devices/system/cpu/cpu0/cpufreq/gpu_oc && echo "GPU Now Clocked at 512 MHz" && sleep 2 && sh /system/xbin/popcorn_gpu;;
      B) sed -i "s|^gpuOC=.*|gpuOC=$OLD|" $initPath && echo "Settings set on boot" && sleep 2 && sh /system/xbin/popcorn_gpu;;
      R) sh /system/xbin/popcorn;;
      X) exit 1;;
      *) echo "Invalid option" && sleep 2 && sh /system/xbin/popcorn_gpu;;
    esac
  fi

