#!/system/bin/sh

#toot toot
echo '\\\\   //\\ ||\\||====||=\\\\'
echo ' \\\\ //=\\\\||\\\\| || ||=//'
echo '  \\//   \\\\| \\|====|| \\\\'

# Make perms all loosey-goosey
[ -d /sys/devices/system/cpu/cpufreq/interactive ] && vanirinteractivegovernorgovernor

# ICUP FUNI CULURSZ
[ -e /sys/class/misc/colorcontrol/v1_offset ] && chown system:system /sys/class/misc/colorcontrol/v1_offset && chmod 0666 /sys/class/misc/colorcontrol/v1_offset
[ -e /sys/class/misc/colorcontrol/multiplier ] && chown system:system /sys/class/misc/colorcontrol/multiplier && chmod 0666 /sys/class/misc/colorcontrol/multiplier
[ -e /sys/devices/platform/omapdss/manager0/gamma ] && chown system:system /sys/devices/platform/omapdss/manager0/gamma && chmod 0666 /sys/devices/platform/omapdss/manager0/gamma
