#!/system/bin/sh
# Consolidated T5UN4MI Script
# PrimeDirective, Sonicxml, DHO, Nuclearmistake
# With inspiration from DroidTh3ory

sync
sysrw

#
# Enable Sysctl Tweaks
#
sysctl -p /system/etc/sysctl.conf

#
# Set SD Card Cache
#
if [ -e /sys/devices/virtual/bdi/179:0/read_ahead_kb ]; then
	echo 2048 > /sys/devices/virtual/bdi/179:0/read_ahead_kb
fi

#RQ_Affinity
for b in /sys/block/*; do echo 1 > $b/queue/rq_affinity; done


#
#
# Sysctl & VM Tweaks
#
### NEW RANDOM VALUES FOR RANDOM SEED HACK
busybox sysctl -e -w kernel.random.read_wakeup_threshold=1024
busybox sysctl -e -w kernel.random.write_wakeup_threshold=2048
busybox sysctl -w fs.file-max=524288
busybox sysctl -w fs.inotify.max_queued_events=32000
busybox sysctl -w kernel.panic=0
busybox sysctl -w kernel.panic_on_oops=1
busybox sysctl -w kernel.msgmni=2048
busybox sysctl -w kernel.msgmax=64000
busybox sysctl -w kernel.shmmax=268435500
busybox sysctl -w kernel.sem=500,512000,64,2048
busybox sysctl -w kernel.threads-max=525810

#
# START wrapper script that brute-forces rngd until it stays alive
#
####
vanirrngdd &

#
# File System Tweaks & Cleanup
#
for m in "/" "/dev" "/proc" "/sys" "/system" "/data" "/data/data" "/cache" "/acct" "/dev/pts" "/dev/cpuctl" "/mnt/asec" "/mnt/obb"; do
    busybox mount -o remount,noatime,nodiratime,discard,noauto_da_alloc,nodev $m
done

echo "10" > /proc/sys/fs/lease-break-time

sync
sysro
