#!/system/bin/sh
# Consolidated T5UN4MI Script
# PrimeDirective, Sonicxml, DHO, Nuclearmistake, aosp
# With inspiration from DroidTh3ory

sync
sysrw

#
# Enable Sysctl Tweaks
#
sysctl -p /system/etc/sysctl.conf

#
# Set SD Card Cache
#
if [ -e /sys/devices/virtual/bdi/179:0/read_ahead_kb ]; then
  echo 256 > /sys/devices/virtual/bdi/179:0/read_ahead_kb
fi

#
# General Queue Tweaks
#
for i in /sys/block/*/queue; do
  echo 512 > $i/nr_requests;
  echo 256 > $i/read_ahead_kb;
  echo 2 > $i/rq_affinity;
  echo 0 > $i/nomerges;
  echo 0 > $i/add_random;
  echo 0 > $i/rotational;
done;

for i in `find /sys/device/platform -name iostats`; do echo "0" > $i; done

#
# File System Tweaks & Cleanup
#
busybox mount -o remount,noatime,noauto_da_alloc,nodiratime,barrier=0,data=writeback /system
for m in "/data" "/cache"; do
  busybox mount -o remount,commit=19,barrier=0,discard,nomblk_io_submit,noauto_da_alloc,errors=continue,noatime,nodiratime,nosuid,nodev,data=writeback $m
done

sync
sysro
