#!/system/xbin/bash
# Sonicxml, Nuclearmistake
# Inspiration from Jakebites and Liberty's liberty.cfg and associated init.d scripts

. /etc/vanir.cfg

#prevent conflicts for people using leantweaks instead
[ -e /etc/init.d/99leantweaks ] && [ $force_override_leantweaks -eq 0 ] && exit


# This allows you to turn SmartReflex on or off
# For MPU
echo "$srMPU" > /sys/kernel/debug/smartreflex/sr_mpu/autocomp
# For Core
echo "$srCORE" > /sys/kernel/debug/smartreflex/sr_core/autocomp
# For IVA
echo "$srIVA" > /sys/kernel/debug/smartreflex/sr_iva/autocomp



# GPU Overclock
echo "$gpuOC" > /sys/devices/system/cpu/cpu0/cpufreq/gpu_oc

# Governor Control
echo "$scaleGov" > /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor

# CPU Control
echo "$maxFreq" > /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq
echo "$minFreq" > /sys/devices/system/cpu/cpu0/cpufreq/scaling_min_freq

### HOTPLUGGING ###
echo "$hotPlug" > /sys/devices/system/cpu/cpu1/online



# Touch Wake
echo "$TWstatus" > /sys/class/misc/touchwake/enabled
echo "$TWdelay" > /sys/class/misc/touchwake/delay




# BLX (Battery Life Extender)
echo "$BLX" > /sys/class/misc/batterylifeextender/charging_limit

# Enable/disable USB fast charging
echo "$ffc" > /sys/kernel/fast_charge/force_fast_charge

# Enabled/disable the low latency mode for the WiFi during screen-off
echo "$wll" > /sys/module/bcmdhd/parameters/wifi_pm




# Selects GAMMA preset to control contrast
echo "$OMAPgamma" > /sys/devices/platform/omapdss/manager0/gamma

# V1 Gamma Offsets
echo "$GammaOffset" > /sys/class/misc/colorcontrol/v1_offset

# Color Multipliers
echo "$ColorSafety" > /sys/class/misc/colorcontrol/safety_enabled
echo "$ColorMult" > /sys/class/misc/colorcontrol/multiplier





# Headset Volume Boost
echo "$VolBoost" > /sys/class/misc/soundcontrol/volume_boost

# High Performance Audio
echo "$HighPerf" > /sys/class/misc/soundcontrol/highperf_enabled
