#!/system/bin/sh
# Nice Tweaks
# PrimeDirective and Sonicxml
# Thanks to mike1986 for the wait for boot code

bash -c "
while busybox [ ! $(logcat -d *:I *:D | grep -c android.intent.action.BOOT_COMPLETED) ]; do sleep 1; done

echo Boot completed... sleeping a little for user apps to launch.
sleep 5
vanirnice" &
