#!/system/bin/sh
# Nice Tweaks
# PrimeDirective and Sonicxml
# Thanks to mike1986 for the wait for boot code

bash -c "
while busybox [ ! $(logcat -d *:I *:D | grep -c android.intent.action.BOOT_COMPLETED) ]; do sleep 1; done
		renice -15 $(pidof com.android.launcher)
		renice -12 $(pidof com.android.chrome)
		renice -12 $(pidof com.google.android.browser)
        renice -11 $(pidof com.google.android.googlequicksearchbox)
        renice -10 $(pidof com.android.phone)
		renice -10 $(pidof com.android.systemui)
		renice -7 $(pidof com.google.android.inputmethod.latin)
        ionice $(pidof com.android.camera) be 0
        ionice $(pidof com.google.android.music) rt 1" &
