PRODUCT_MAKEFILES := \
    $(LOCAL_DIR)/vanir_anzu.mk \
    $(LOCAL_DIR)/vanir_bacon.mk \
    $(LOCAL_DIR)/vanir_coconut.mk \
    $(LOCAL_DIR)/vanir_codinalte.mk \
    $(LOCAL_DIR)/vanir_deb.mk \
    $(LOCAL_DIR)/vanir_d2lte.mk \
    $(LOCAL_DIR)/vanir_d710.mk \
    $(LOCAL_DIR)/vanir_d800.mk \
    $(LOCAL_DIR)/vanir_d801.mk \
    $(LOCAL_DIR)/vanir_d802.mk \
    $(LOCAL_DIR)/vanir_d803.mk \
    $(LOCAL_DIR)/vanir_dlx.mk \
    $(LOCAL_DIR)/vanir_e980.mk \
    $(LOCAL_DIR)/vanir_evita.mk \
    $(LOCAL_DIR)/vanir_falcon.mk \
    $(LOCAL_DIR)/vanir_find5.mk \
    $(LOCAL_DIR)/vanir_find7.mk \
    $(LOCAL_DIR)/vanir_flo.mk \
    $(LOCAL_DIR)/vanir_geeb.mk \
    $(LOCAL_DIR)/vanir_gee.mk \
    $(LOCAL_DIR)/vanir_golden.mk \
    $(LOCAL_DIR)/vanir_grouper.mk \
    $(LOCAL_DIR)/vanir_haida.mk \
    $(LOCAL_DIR)/vanir_hallon.mk \
    $(LOCAL_DIR)/vanir_hammerhead.mk \
    $(LOCAL_DIR)/vanir_hlte.mk \
    $(LOCAL_DIR)/vanir_honami.mk \
    $(LOCAL_DIR)/vanir_i605.mk \
    $(LOCAL_DIR)/vanir_i9100g.mk \
    $(LOCAL_DIR)/vanir_i9300.mk \
    $(LOCAL_DIR)/vanir_i9305.mk \
    $(LOCAL_DIR)/vanir_i9500.mk \
    $(LOCAL_DIR)/vanir_iyokan.mk \
    $(LOCAL_DIR)/vanir_janice.mk \
    $(LOCAL_DIR)/vanir_jewel.mk \
    $(LOCAL_DIR)/vanir_jflte.mk \
    $(LOCAL_DIR)/vanir_klte.mk \
    $(LOCAL_DIR)/vanir_ls980.mk \
    $(LOCAL_DIR)/vanir_m4.mk \
    $(LOCAL_DIR)/vanir_m7att.mk \
    $(LOCAL_DIR)/vanir_m7spr.mk \
    $(LOCAL_DIR)/vanir_m7tmo.mk \
    $(LOCAL_DIR)/vanir_m7ul.mk \
    $(LOCAL_DIR)/vanir_m7vzw.mk \
    $(LOCAL_DIR)/vanir_m8.mk \
    $(LOCAL_DIR)/vanir_manta.mk \
    $(LOCAL_DIR)/vanir_maguro.mk \
    $(LOCAL_DIR)/vanir_mango.mk \
    $(LOCAL_DIR)/vanir_mako.mk \
    $(LOCAL_DIR)/vanir_maserati.mk \
    $(LOCAL_DIR)/vanir_mondrianwifi.mk \
    $(LOCAL_DIR)/vanir_moto_msm8960.mk \
    $(LOCAL_DIR)/vanir_moto_msm8960dt.mk \
    $(LOCAL_DIR)/vanir_n1.mk \
    $(LOCAL_DIR)/vanir_n5100.mk \
    $(LOCAL_DIR)/vanir_n5110.mk \
    $(LOCAL_DIR)/vanir_n5120.mk \
    $(LOCAL_DIR)/vanir_nicki.mk \
    $(LOCAL_DIR)/vanir_p3110.mk \
    $(LOCAL_DIR)/vanir_p880.mk \
    $(LOCAL_DIR)/vanir_pollux.mk \
    $(LOCAL_DIR)/vanir_pollux_windy.mk \
    $(LOCAL_DIR)/vanir_satsuma.mk \
    $(LOCAL_DIR)/vanir_sirius.mk \
    $(LOCAL_DIR)/vanir_skomer.mk \
    $(LOCAL_DIR)/vanir_smultron.mk \
    $(LOCAL_DIR)/vanir_t0lte.mk \
    $(LOCAL_DIR)/vanir_tf700t.mk \
    $(LOCAL_DIR)/vanir_tf701t.mk \
    $(LOCAL_DIR)/vanir_taoshan.mk \
    $(LOCAL_DIR)/vanir_tilapia.mk \
    $(LOCAL_DIR)/vanir_toro.mk \
    $(LOCAL_DIR)/vanir_toroplus.mk \
    $(LOCAL_DIR)/vanir_tsubasa.mk \
    $(LOCAL_DIR)/vanir_urushi.mk \
    $(LOCAL_DIR)/vanir_v500.mk \
    $(LOCAL_DIR)/vanir_ville.mk \
    $(LOCAL_DIR)/vanir_vs980.mk \
    $(LOCAL_DIR)/vanir_wx_na_wf.mk \
    $(LOCAL_DIR)/vanir_yuga.mk
