PRODUCT_MAKEFILES := \
    $(LOCAL_DIR)/vanir_deb.mk \
    $(LOCAL_DIR)/vanir_d2lte.mk \
    $(LOCAL_DIR)/vanir_d710.mk \
    $(LOCAL_DIR)/vanir_d800.mk \
    $(LOCAL_DIR)/vanir_d801.mk \
    $(LOCAL_DIR)/vanir_d802.mk \
    $(LOCAL_DIR)/vanir_d803.mk \
    $(LOCAL_DIR)/vanir_dlx.mk \
    $(LOCAL_DIR)/vanir_e980.mk \
    $(LOCAL_DIR)/vanir_flo.mk \
    $(LOCAL_DIR)/vanir_geeb.mk \
    $(LOCAL_DIR)/vanir_gee.mk \
    $(LOCAL_DIR)/vanir_grouper.mk \
    $(LOCAL_DIR)/vanir_hammerhead.mk \
    $(LOCAL_DIR)/vanir_hlte.mk \
    $(LOCAL_DIR)/vanir_i605.mk \
    $(LOCAL_DIR)/vanir_i9100g.mk \
    $(LOCAL_DIR)/vanir_i9300.mk \
    $(LOCAL_DIR)/vanir_i9305.mk \
    $(LOCAL_DIR)/vanir_jewel.mk \
    $(LOCAL_DIR)/vanir_jflte.mk \
    $(LOCAL_DIR)/vanir_ls980.mk \
    $(LOCAL_DIR)/vanir_m7att.mk \
    $(LOCAL_DIR)/vanir_m7spr.mk \
    $(LOCAL_DIR)/vanir_m7tmo.mk \
    $(LOCAL_DIR)/vanir_m7ul.mk \
    $(LOCAL_DIR)/vanir_m7vzw.mk \
    $(LOCAL_DIR)/vanir_manta.mk \
    $(LOCAL_DIR)/vanir_maguro.mk \
    $(LOCAL_DIR)/vanir_mako.mk \
    $(LOCAL_DIR)/vanir_maserati.mk \
    $(LOCAL_DIR)/vanir_p880.mk \
    $(LOCAL_DIR)/vanir_pollux.mk \
    $(LOCAL_DIR)/vanir_pollux_windy.mk \
    $(LOCAL_DIR)/vanir_t0lteatt.mk \
    $(LOCAL_DIR)/vanir_t0ltetmo.mk \
    $(LOCAL_DIR)/vanir_tilapia.mk \
    $(LOCAL_DIR)/vanir_toro.mk \
    $(LOCAL_DIR)/vanir_toroplus.mk \
    $(LOCAL_DIR)/vanir_vs980.mk \
    $(LOCAL_DIR)/vanir_xt907.mk \
    $(LOCAL_DIR)/vanir_xt925.mk \
    $(LOCAL_DIR)/vanir_xt926.mk \
    $(LOCAL_DIR)/vanir_xt1053.mk \
    $(LOCAL_DIR)/vanir_xt1058.mk \
    $(LOCAL_DIR)/vanir_xt1060.mk \
    $(LOCAL_DIR)/vanir_yuga.mk
