PRODUCT_MAKEFILES := \
    $(LOCAL_DIR)/vanir_deb.mk \
    $(LOCAL_DIR)/vanir_d2att.mk \
    $(LOCAL_DIR)/vanir_d2spr.mk \
    $(LOCAL_DIR)/vanir_d2tmo.mk \
    $(LOCAL_DIR)/vanir_d2vzw.mk \
	$(LOCAL_DIR)/vanir_e975.mk \
	$(LOCAL_DIR)/vanir_e980.mk \
    $(LOCAL_DIR)/vanir_flo.mk \
    $(LOCAL_DIR)/vanir_grouper.mk \
    $(LOCAL_DIR)/vanir_hercules.mk \
    $(LOCAL_DIR)/vanir_i605.mk \
    $(LOCAL_DIR)/vanir_i9300.mk \
    $(LOCAL_DIR)/vanir_i9305.mk \
    $(LOCAL_DIR)/vanir_jewel.mk \
    $(LOCAL_DIR)/vanir_m7att.mk \
    $(LOCAL_DIR)/vanir_m7spr.mk \
    $(LOCAL_DIR)/vanir_m7tmo.mk \
    $(LOCAL_DIR)/vanir_m7ul.mk \
    $(LOCAL_DIR)/vanir_m7vzw.mk \
    $(LOCAL_DIR)/vanir_manta.mk \
    $(LOCAL_DIR)/vanir_maguro.mk \
    $(LOCAL_DIR)/vanir_mako.mk \
    $(LOCAL_DIR)/vanir_maserati.mk \
    $(LOCAL_DIR)/vanir_p880.mk \
    $(LOCAL_DIR)/vanir_pollux.mk \
    $(LOCAL_DIR)/vanir_jfltevzw.mk \
    $(LOCAL_DIR)/vanir_jflteatt.mk \
    $(LOCAL_DIR)/vanir_jfltecan.mk \
    $(LOCAL_DIR)/vanir_jfltecri.mk \
    $(LOCAL_DIR)/vanir_jfltespr.mk \
    $(LOCAL_DIR)/vanir_jfltetmo.mk \
    $(LOCAL_DIR)/vanir_t0lteatt.mk \
    $(LOCAL_DIR)/vanir_t0ltetmo.mk \
    $(LOCAL_DIR)/vanir_toro.mk \
    $(LOCAL_DIR)/vanir_toroplus.mk \
    $(LOCAL_DIR)/vanir_p700.mk \
    $(LOCAL_DIR)/vanir_tilapia.mk \
    $(LOCAL_DIR)/vanir_yuga.mk
