#!/bin/sh
#
# Squish a Vanir otapackage for distribution
# credit for original version: CM
#

. $ANDROID_BUILD_TOP/vendor/vanir/tools/functions

OUT_TARGET_HOST=`uname -a | grep Darwin`
if [ -z "$OUT_TARGET_HOST" ]
then
   OUT_TARGET_HOST=linux-x86
   MD5=md5sum
   XARGS="xargs --max-args=1 --max-procs `grep 'processor' /proc/cpuinfo|wc -l`"
   SED=sed
else
   OUT_TARGET_HOST=darwin-x86
   MD5=md5
   XARGS="xargs -n 1 -P `sysctl hw.ncpu | awk '{print $2}'`"
   SED=gsed
fi

if [ -z "$OUT" -o ! -d "$OUT" ]; then
    echo -e $CL_RED"ERROR: $0 only works with a full build environment. $OUT should exist."$CL_RST
    exit 1
fi

if [ "$TARGET_BUILD_TYPE" = "debug" ]; then
    OTAPACKAGE=$OUT/${TARGET_PRODUCT}_debug-ota-$TARGET_BUILD_VARIANT.$USER.zip
elif [ "$TARGET_BUILD_VARIANT" = "userdebug" ]; then
    OTAPACKAGE=$OUT/$TARGET_PRODUCT-ota-eng.$USER.zip
else
#    OTAPACKAGE=$OUT/$TARGET_PRODUCT-ota-$TARGET_BUILD_VARIANT.$USER.zip
    OTAPACKAGE=$OUT/$TARGET_PRODUCT-ota-eng.$USER.zip
fi
if [ ! -f "$OTAPACKAGE" ]; then
    echo -e $CL_RED"$OTAPACKAGE doesn't exist!"$CL_RST;
    exit 1
fi

OPTICHARGER=$ANDROID_BUILD_TOP/vendor/vanir/tools/opticharger
QUIET=-q
DELETE_BINS="applypatch applypatch_static check_prereq recovery updater"

# Some products want a squashfs for xbin for space
case "$TARGET_PRODUCT" in
    cyanogen_dream_sapphire) WANT_SQUASHFS=1 ;;
    *) WANT_SQUASHFS=0 ;;
esac

if [ "$WANT_SQUASHFS" -eq 1 ]; then
    fatal=0
    MKSQUASHFS_VER_REQ=4
    if type mksquashfs >/dev/null 2>&1; then
        if mksquashfs -version | grep -q "version $MKSQUASHFS_VER_REQ"; then :; else
            echo
            echo "ERROR: mksquashfs must be at least version $MKSQUASHFS_VER_REQ for this build."
                fatal=1
            fi
        else
            echo
            echo "ERROR: $TARGET_PRODUCT requires mksquashfs."
            fatal=1
        fi

        if [ "$fatal" -ne 0 ]; then
            echo
            echo "       Unoptimized package is still available at"
            echo "         $OTAPACKAGE"
            exit $fatal
        fi
fi

REPACK=$OUT/repack.d
printf "Sanitizing environment..."
rm -rf $REPACK
mkdir -p $REPACK
echo

# Unpack the otapackage and opticharge all apks
mkdir $REPACK/ota
(
cd $REPACK/ota
printf "Unpacking $OTAPACKAGE..."
unzip $QUIET $OTAPACKAGE
cp -r $OUT/data $REPACK/ota/data
echo

# Move all apks to the same directory so xargs can
# use also with framework-res.apk. This allow process
# framework-res.apk in parallel with other apks
mkdir -p $REPACK/parallel
cd $REPACK/parallel
cp $REPACK/ota/system/framework/framework-res.apk .
cp $REPACK/ota/system/app/*.apk .

# Do optimization in parallel
find ./ -name \*.apk | $XARGS $OPTICHARGER

# Move optimized apks to repack directory
mv -f $REPACK/parallel/framework-res.apk $REPACK/ota/system/framework/framework-res.apk
mv -f $REPACK/parallel/*.apk $REPACK/ota/system/app/

# Return to directory
cd $REPACK/ota
rm -rf $REPACK/parallel
)


if [ "$WANT_SQUASHFS" -eq 1 ]; then
    squash_opts="-force-uid 1000 -force-gid 1000 -no-progress -noappend -no-exports -no-recovery"
    updater=$REPACK/ota/META-INF/com/google/android/updater-script

    # Relocate su
    cp -a $REPACK/ota/system/xbin $REPACK/_xbin/
    rm -f $REPACK/_xbin/su $REPACK/ota/system/bin/su
    mv $REPACK/ota/system/xbin/su $REPACK/ota/system/bin/su
    chmod -R 555 $REPACK/_xbin/*

    # Create symlinks for su and busybox (since updater-script can't work on the squashfs filesystem).
    # Forgive me for the regex hell here.
    ln -s ../bin/su $REPACK/_xbin/su
    for link in `sed -n -e's/,//g' -e'/symlink(.*busybox/,/xbin.*);/p' $updater | tr '"' '\n' | sed -n -e'\,/system/xbin/,s,/system/xbin/,,p'`
    do
        ln -s busybox $REPACK/_xbin/$link
    done

    # Create the squashfs with new and improved symlinkage!
    mksquashfs $REPACK/_xbin/* $REPACK/_xbin.sqf $squash_opts
    rm -rf $REPACK/ota/system/xbin/*
    mv $REPACK/_xbin.sqf $REPACK/ota/system/xbin/xbin.sqf
    chmod 444 $REPACK/ota/system/xbin/xbin.sqf

    # Remove xbin stuff and fix up updater-script
    $SED -i -e's,system/xbin/su,system/bin/su,g' -e'/xbin/d' $updater
fi

# Fix build.prop
$SED -i \
     -e '/ro\.kernel\.android\.checkjni/d' \
     -e '/ro\.build\.type/s/eng/user/' \
     $REPACK/ota/system/build.prop
	
# Fix build.prop step 2
echo "Fixing \"move hyst\" property name... whoever put a space in it is a butthead."
$SED 's/movehyst/move hyst/g' -i $REPACK/ota/system/build.prop

# Delete unnecessary binaries
# ( cd $REPACK/ota/system/bin; echo $DELETE_BINS | xargs rm -f; )

# Delete leftover wireless driver
# rm -rf $REPACK/ota/system/lib/modules/*/kernel/drivers/net

# No need for recovery
rm -rf $REPACK/ota/recovery

# Strip modules
[ -d $REPACK/ota/system/lib/modules ] && \
    find $REPACK/ota/system/lib/modules -name "*.ko" -print0 | xargs -0 arm-eabi-strip --strip-unneeded

## unbreak non-tuna stuff
# Fix Beats
#rm -f $REPACK/ota/system/etc/audio_effects.conf
#rm -f $REPACK/ota/system/etc/media_profiles.xml
#rm -f $REPACK/ota/system/lib/bluez-plugin/audio.so
#rm -f $REPACK/ota/system/lib/soundfx/libaudiopreprocessing.so
#rm -f $REPACK/ota/system/lib/soundfx/libbundlewrapper.so
#rm -f $REPACK/ota/system/lib/soundfx/libreverbwrapper.so
#rm -f $REPACK/ota/system/lib/soundfx/libvisualizer.so
#rm -f $REPACK/ota/system/lib/libSR_AudioIn.so
#cp -f $ANDROID_BUILD_TOP/vendor/vanir/proprietary/tuna/etc/audio_effects.conf $REPACK/ota/system/etc/audio_effects.conf
#cp -f $ANDROID_BUILD_TOP/vendor/vanir/proprietary/tuna/etc/media_profiles.xml $REPACK/ota/system/etc/media_profiles.xml
#cp -f $ANDROID_BUILD_TOP/vendor/vanir/proprietary/tuna/lib/bluez-plugin/audio.so $REPACK/ota/system/lib/bluez-plugin/audio.so
#cp -f $ANDROID_BUILD_TOP/vendor/vanir/proprietary/tuna/lib/soundfx/libaudiopreprocessing.so $REPACK/ota/system/lib/soundfx/libaudiopreprocessing.so
#cp -f $ANDROID_BUILD_TOP/vendor/vanir/proprietary/tuna/lib/soundfx/libbundlewrapper.so $REPACK/ota/system/lib/soundfx/libbundlewrapper.so
#cp -f $ANDROID_BUILD_TOP/vendor/vanir/proprietary/tuna/lib/soundfx/libreverbwrapper.so $REPACK/ota/system/lib/soundfx/libreverbwrapper.so
#cp -f $ANDROID_BUILD_TOP/vendor/vanir/proprietary/tuna/lib/soundfx/libvisualizer.so $REPACK/ota/system/lib/soundfx/libvisualizer.so
#cp -f $ANDROID_BUILD_TOP/vendor/vanir/proprietary/tuna/lib/libSR_AudioIn.so $REPACK/ota/system/lib/libSR_AudioIn.so

# Other files
#rm -f $REPACK/ota/system/vendor/firmware/ducati-m3.bin
#cp -f $ANDROID_BUILD_TOP/vendor/vanir/proprietary/tuna/vendor/firmware/ducati-m3.bin $REPACK/ota/system/vendor/firmware/ducati-m3.bin

# Determine what to name the new signed package
MODVERSION=`sed -n -e'/ro\.modversion/s/^.*=//p' $REPACK/ota/system/build.prop`
OUTVERSION="$TARGET_PRODUCT"_"$MODVERSION"
OUTFILE=$OUT/$OUTVERSION.zip

# Pack it up and sign
printf "Zipping package..."
( cd $REPACK/ota; zip $QUIET -r $REPACK/update.zip . )
echo
printf "Signing package..."
SECURITYDIR=$ANDROID_BUILD_TOP/build/target/product/security
java -Xmx1024m \
    -jar $ANDROID_BUILD_TOP/out/host/$OUT_TARGET_HOST/framework/signapk.jar \
    -w $SECURITYDIR/testkey.x509.pem $SECURITYDIR/testkey.pk8 \
    $REPACK/update.zip $OUTFILE
echo
printf "Cleaning up..."
rm -rf $REPACK
echo

# Create a md5 checksum image of the repacked package
(
echo ""
echo ""
echo $CL_GRN"================  "$CL_RST OTA package information $CL_GRN"  ================"$CL_RST
echo ""
echo $CL_BLU"Product name:"$CL_RST $TARGET_PRODUCT-ota-eng.$USER.zip

img=`basename $OUTFILE`
cd `dirname $OUTFILE`
STRING="$TARGET_PRODUCT-ota-eng.$USER.zip"
OTASIZE=`ls -lah $STRING | awk '{ print $5}' `
echo $CL_BLU"Package Size: "$CL_YLW "$OTASIZE" $CL_RST
echo $CL_BLU"Target Location: " $CL_RST
echo $CL_YLW"$OUT/$TARGET_PRODUCT-ota-eng.$USER.zip" $CL_RST
echo ""

$MD5 $img >$img.md5
ZIPSIZE=`ls -lah $OUTFILE | awk '{ print $5}' `
echo $CL_GRN"================"$CL_RST $TARGET_PRODUCT-$TARGET_BUILD_VARIANT: $CL_RED"completed"$CL_RST $CL_GRN"================"$CL_RST
echo ""
echo $CL_BLU"Product name:"$CL_RST $OUTVERSION.zip
echo $CL_BLU"Package Size: "$CL_YLW"$ZIPSIZE     "
echo $CL_BLU"md5:"$CL_RST $CL_YLW" $(cat $img.md5 | awk '{ print $1 }')"$CL_RST
echo $CL_BLU"Target location:"$CL_RST
echo $CL_YLW $OUTFILE $CL_RST
echo ""
echo ""
)

exit 0
